name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Notify slack about deployment starting
        id: slack
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          channel: ###
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: In progress... 😱
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install Dependencies
        working-directory: .
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Fetch env vars
        working-directory: .
        run: |
          echo "APP_VERSION=$APP_VERSION" >> .env.production
        env:
          APP_VERSION: ${{ github.sha }}
      - name: Deploy code
        working-directory: .
        run: |
          ### deployment steps
        env:
          APP_ENV: "production"
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
          BUGSNAG_APP_VERSION: ${{ github.sha }}
      - name: Update slack message on success
        uses: someimportantcompany/github-actions-slack-message@v1
        if: success()
        with:
          channel: ###
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          color: success
          text: Deployed, it worked! ✨🦄🌈✨ 😮‍💨
          message-id: ${{ steps.slack.outputs.message-id }}
      - name: Update slack message on failure
        uses: someimportantcompany/github-actions-slack-message@v1
        if: failure()
        with:
          channel: ###
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          color: failed
          text: Failed, oops... 🔥☠️🔥
          message-id: ${{ steps.slack.outputs.message-id }}
