name: Unit test suite

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
    branches:
      - master

jobs:
  phpunit:

    name: Run unit tests
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpstan, phpunit
      - name: Project Setup
        working-directory: .
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute tests
        env:
          APP_ENV: testing
        working-directory: .
        run: |
          composer test:unit
