framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Characters\Domain\Events\CharacterCreated: async
            App\Characters\Domain\Events\CharacterUpdated: async
            App\Characters\Domain\Events\CharacterDeleted: async
