controllers:
    resource: ../src/Characters/Infrastructure/Controllers
    type: attribute

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }